FROM postgres:11.4

MAINTAINER saraivaufc <saraiva.ufc@gmail.com>

ENV LANG en_US.UTF-8  

ENV LANGUAGE en_US:en  

ENV LC_ALL en_US.UTF-8 

RUN apt-get update && apt-get install -y postgresql-11-postgis-2.5 postgis