FROM postgres:14

MAINTAINER saraivaufc <saraiva.ufc@gmail.com>

ENV LANG en_US.UTF-8  

ENV LANGUAGE en_US:en  

ENV LC_ALL en_US.UTF-8 

RUN apt-get update && apt-get install -y postgresql-14-postgis-3 postgis
